### ISSUE TITLE
Missing license 

### ISSUE THREAD

**Issue by aar9nk** [alinemartins/amazon-alexa-page#1]
Add a license / readme / good commit message to every project!
Please double check what you've added :)
Even if it is some quick example people will notice !
Add license file in github and on the right a pop up will ask what license you want, i usually use mit

**Comment by aar9nk** [comment]
I don't mean to hassle you , just complete it if you get a chance in the future!

**Comment by alinemartins** [comment]
Thank you, Aaron. I've just added a license. I discovered that there is a checklist of community standards. I will completed. Thank you again.
